from __future__ import annotations

from sqlalchemy.orm import Session

from . import models


STARTER_TAGS = [
    "docker",
    "debian",
    "ubuntu",
    "raspberry-pi",
    "windows",
    "cloudflare",
    "portainer",
    "home-assistant",
    "media",
    "graphics",
    "testing",
    "production",
    "critical",
    "needs-backup",
    "public-url",
    "private-only",
    "migrate-later",
]


STARTER_COMMANDS = [
    {
        "name": "SSH into server",
        "category": "SSH",
        "applies_to_type": "generic",
        "command_template": "ssh {{username}}@{{host}}",
        "short_description": "Open an SSH session to a server.",
        "help_low": "Connects to the selected server over SSH.",
        "help_high": "Run this on your local computer to start a remote shell on the server. Replace the username and host if needed.",
        "where_to_run": "Local computer before SSH",
        "risk_level": "safe",
    },
    {
        "name": "Debian update",
        "category": "Debian / Ubuntu",
        "command_template": "sudo apt update\nsudo apt upgrade -y",
        "short_description": "Refresh package lists and install available updates.",
        "help_low": "Updates Debian or Ubuntu packages.",
        "help_high": "Run this inside SSH on the Linux host. It downloads package metadata, then installs available package updates.",
        "where_to_run": "Remote SSH host",
        "risk_level": "caution",
    },
    {
        "name": "Debian reboot",
        "category": "Debian / Ubuntu",
        "command_template": "sudo reboot",
        "short_description": "Reboot the server.",
        "help_low": "Restarts the server.",
        "help_high": "This disconnects SSH and interrupts services until the host finishes booting.",
        "where_to_run": "Remote SSH host",
        "risk_level": "caution",
    },
    {
        "name": "Check disk space",
        "category": "Storage",
        "command_template": "df -h",
        "short_description": "Show mounted filesystem usage.",
        "help_low": "Shows free and used disk space.",
        "help_high": "Run inside SSH to see whether a filesystem is close to full. The -h option makes sizes human-readable.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Check memory",
        "category": "Common",
        "command_template": "free -h",
        "short_description": "Show memory usage.",
        "help_low": "Shows RAM and swap usage.",
        "help_high": "Run inside SSH to check available memory. Linux may use memory for cache; that is usually normal.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Check system load",
        "category": "Common",
        "command_template": "uptime",
        "short_description": "Show uptime and load average.",
        "help_low": "Shows how long a Linux server has been running and a quick load summary.",
        "help_high": "Run this in a Linux terminal or inside SSH on the selected server. The output shows current time, uptime, logged-in users, and load averages for the last 1, 5, and 15 minutes. It does not change anything.",
        "where_to_run": "Linux terminal or remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Check Docker service status",
        "category": "Docker",
        "command_template": "sudo systemctl status docker",
        "short_description": "Show whether Docker is running.",
        "help_low": "Checks the Docker system service.",
        "help_high": "Use this when containers are not responding and you need to see whether the Docker daemon is active.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Restart Docker service",
        "category": "Docker",
        "command_template": "sudo systemctl restart docker",
        "short_description": "Restart Docker on the host.",
        "help_low": "Restarts Docker and may interrupt containers.",
        "help_high": "Use carefully. Restarting Docker can interrupt running containers and connected services.",
        "where_to_run": "Remote SSH host",
        "risk_level": "caution",
    },
    {
        "name": "Show running Docker containers",
        "category": "Docker",
        "command_template": "docker ps",
        "short_description": "List currently running containers.",
        "help_low": "Shows running containers.",
        "help_high": "Use this inside SSH on a Docker host to see container names, images, uptime, and exposed ports.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Show all Docker containers",
        "category": "Docker",
        "command_template": "docker ps -a",
        "short_description": "List running and stopped containers.",
        "help_low": "Shows all containers, including stopped ones.",
        "help_high": "Useful when a service disappeared from docker ps because the container exited.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Show Docker disk usage",
        "category": "Docker",
        "command_template": "docker system df",
        "short_description": "Show Docker image, container, and volume disk usage.",
        "help_low": "Shows how much disk Docker is using.",
        "help_high": "Use this before pruning Docker data. It helps identify whether images, containers, or volumes are using space.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Docker Compose start or update current stack",
        "category": "Docker Compose",
        "command_template": "docker compose up -d",
        "short_description": "Start or recreate the current Compose stack.",
        "help_low": "Starts the app from the current docker-compose.yml folder.",
        "help_high": "Run this from the folder containing docker-compose.yml. It creates missing containers and starts them in the background.",
        "where_to_run": "Remote SSH host inside service folder",
        "risk_level": "safe",
    },
    {
        "name": "Docker Compose rebuild stack",
        "category": "Docker Compose",
        "command_template": "docker compose up -d --build",
        "short_description": "Rebuild and restart a Compose stack.",
        "help_low": "Rebuilds the app and restarts containers.",
        "help_high": "Run from the Compose folder after code or Dockerfile changes. It can briefly interrupt the service.",
        "where_to_run": "Remote SSH host inside service folder",
        "risk_level": "caution",
    },
    {
        "name": "Docker Compose logs",
        "category": "Logs",
        "command_template": "docker compose logs -f",
        "short_description": "Follow live logs for the current Compose stack.",
        "help_low": "Shows live logs. Press Ctrl+C to stop watching.",
        "help_high": "This reads logs from containers in the current Compose project and follows new lines. Press Ctrl+C; that does not stop the containers.",
        "where_to_run": "Remote SSH host inside service folder",
        "risk_level": "safe",
    },
    {
        "name": "Docker Compose stop stack",
        "category": "Docker Compose",
        "command_template": "docker compose down",
        "short_description": "Stop the current Compose stack.",
        "help_low": "Stops containers for this app.",
        "help_high": "Run only from the right Compose folder. This stops the service until you start it again.",
        "where_to_run": "Remote SSH host inside service folder",
        "risk_level": "caution",
    },
    {
        "name": "Docker Compose stop and remove volumes",
        "category": "Danger Zone",
        "command_template": "docker compose down -v",
        "short_description": "Stop stack and remove Compose-managed volumes.",
        "help_low": "Danger: can remove service data stored in volumes.",
        "help_high": "This can delete persistent data if the service stores important files in Docker volumes. Read backup notes before using it.",
        "where_to_run": "Remote SSH host inside service folder",
        "risk_level": "destructive",
    },
    {
        "name": "Clone GitHub repo",
        "category": "Git / GitHub",
        "command_template": "cd {{parent_folder}}\ngit clone {{repo_url}}\ncd {{repo_folder}}",
        "short_description": "Clone a repository and enter its folder.",
        "help_low": "Downloads a GitHub repo to the server.",
        "help_high": "Run this where you keep Docker projects. Check the repo URL before running.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Update GitHub repo",
        "category": "Git / GitHub",
        "command_template": "cd {{repo_folder}}\ngit pull",
        "short_description": "Pull latest code from GitHub.",
        "help_low": "Updates the local repo folder from GitHub.",
        "help_high": "Run this inside the service repository. If there are local changes, Git may ask you to resolve them first.",
        "where_to_run": "Remote SSH host inside repo folder",
        "risk_level": "safe",
    },
    {
        "name": "Update GitHub Docker app",
        "category": "Docker Compose",
        "command_template": "cd {{repo_folder}}\ngit pull\ndocker compose up -d --build\ndocker compose logs -f",
        "short_description": "Pull, rebuild, restart, and watch logs.",
        "help_low": "Updates a Docker app from GitHub and watches logs.",
        "help_high": "Run inside SSH. Confirm the repo folder is correct before copying this. Press Ctrl+C to stop watching logs after startup looks healthy.",
        "where_to_run": "Remote SSH host inside repo folder",
        "risk_level": "caution",
    },
    {
        "name": "Force reset repo to GitHub",
        "category": "Danger Zone",
        "command_template": "cd {{repo_folder}}\ngit fetch origin\ngit reset --hard origin/main",
        "short_description": "Discard local changes and match GitHub main.",
        "help_low": "Danger: discards local changes.",
        "help_high": "Use only when you are sure local changes are unwanted. This can erase uncommitted work.",
        "where_to_run": "Remote SSH host inside repo folder",
        "risk_level": "dangerous",
    },
    {
        "name": "Check listening ports",
        "category": "Networking",
        "command_template": "sudo ss -tulpn",
        "short_description": "Show listening network ports and processes.",
        "help_low": "Shows what ports are open on the server.",
        "help_high": "Useful for finding local services and port conflicts. The process column may require sudo.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Find what is using a port",
        "category": "Networking",
        "command_template": "sudo ss -tulpn | grep ':{{port}}'",
        "short_description": "Search listening sockets for a specific port.",
        "help_low": "Finds what is using a port.",
        "help_high": "Replace the port variable with the port you care about. Useful before assigning a new service port.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Cloudflared quick tunnel",
        "category": "Cloudflare Tunnel",
        "command_template": "cloudflared tunnel --url http://localhost:{{port}}",
        "short_description": "Create a temporary TryCloudflare tunnel.",
        "help_low": "Creates a temporary public URL for a local port.",
        "help_high": "Use only when you intentionally want to expose a local service. Record the generated URL if you need it later.",
        "where_to_run": "Remote SSH host",
        "risk_level": "caution",
    },
    {
        "name": "Docker Compose pull images",
        "category": "Docker Compose",
        "command_template": "docker compose pull",
        "short_description": "Pull newer images for the current Compose stack.",
        "help_low": "Downloads newer Docker images without starting containers.",
        "help_high": "Run from the folder containing compose.yaml or docker-compose.yml. Follow it with docker compose up -d when you are ready to recreate containers.",
        "where_to_run": "Remote SSH host inside service folder",
        "risk_level": "safe",
    },
    {
        "name": "Docker Compose restart one service",
        "category": "Docker Compose",
        "command_template": "docker compose restart {{service_name}}",
        "short_description": "Restart one service in the current Compose project.",
        "help_low": "Restarts one Compose service.",
        "help_high": "Run from the Compose folder. Replace the service name with the service key from the compose file, not necessarily the display name.",
        "where_to_run": "Remote SSH host inside service folder",
        "risk_level": "caution",
    },
    {
        "name": "Docker Compose show config",
        "category": "Docker Compose",
        "command_template": "docker compose config",
        "short_description": "Render and validate the merged Compose configuration.",
        "help_low": "Checks what Docker Compose sees after variables and includes.",
        "help_high": "Useful before starting a stack. It can reveal missing environment variables, invalid YAML, or unexpected paths.",
        "where_to_run": "Remote SSH host inside service folder",
        "risk_level": "safe",
    },
    {
        "name": "Docker container inspect",
        "category": "Docker",
        "command_template": "docker inspect {{container_name}}",
        "short_description": "Show detailed metadata for one Docker container.",
        "help_low": "Shows ports, mounts, labels, networks, and restart settings.",
        "help_high": "Use when documenting a container. The output can be long; paste useful snippets into Smart Paste or notes.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Docker container stats",
        "category": "Docker",
        "command_template": "docker stats",
        "short_description": "Show live CPU and memory usage for containers.",
        "help_low": "Shows live container resource use. Press Ctrl+C to stop.",
        "help_high": "This is a read-only live view. It helps find a container using too much CPU, memory, or network.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Docker prune unused images",
        "category": "Danger Zone",
        "command_template": "docker image prune -a",
        "short_description": "Remove unused Docker images.",
        "help_low": "Danger: removes images not currently used by containers.",
        "help_high": "This can free disk space, but old rollback images may disappear. It should not remove named volumes.",
        "where_to_run": "Remote SSH host",
        "risk_level": "dangerous",
    },
    {
        "name": "Find large folders",
        "category": "Storage",
        "command_template": "sudo du -h --max-depth=1 {{folder}} | sort -h",
        "short_description": "Find which subfolders are using space.",
        "help_low": "Shows folder sizes one level deep.",
        "help_high": "Use this when disk space is low. Start with /srv, /var, or a service data folder.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Tail system service logs",
        "category": "Logs",
        "command_template": "sudo journalctl -u {{service_name}} -f",
        "short_description": "Follow logs for a systemd service.",
        "help_low": "Shows live logs for one Linux service. Press Ctrl+C to stop.",
        "help_high": "Useful for Docker, smbd, ssh, and other system services. This does not stop or restart anything.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Restart SMB",
        "category": "Networking",
        "command_template": "sudo systemctl restart smbd\nsudo systemctl status smbd --no-pager",
        "short_description": "Restart Samba file sharing and check status.",
        "help_low": "Restarts SMB shares and shows status.",
        "help_high": "Use when Windows shares are not responding. Existing transfers may be interrupted.",
        "where_to_run": "Remote SSH host",
        "risk_level": "caution",
    },
    {
        "name": "Check failed system services",
        "category": "Recovery",
        "command_template": "systemctl --failed",
        "short_description": "List failed systemd units.",
        "help_low": "Shows Linux services that failed.",
        "help_high": "Run this after boot or when something feels broken. Follow up with journalctl for a specific unit.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Install Earlyoom",
        "category": "System / Stability",
        "applies_to_type": "generic",
        "command_template": "sudo apt update\nsudo apt install -y earlyoom\nsudo systemctl enable --now earlyoom\nsudo systemctl status earlyoom --no-pager",
        "short_description": "Install and enable Earlyoom to reduce full-system lockups during low-memory conditions.",
        "long_description": "Earlyoom is a lightweight low-memory watchdog for Linux. It helps keep a server responsive by monitoring available RAM and swap. If memory drops below configured thresholds, Earlyoom can terminate the most appropriate process before the machine reaches a hard lockup state. This is especially useful on small Docker hosts, Frigate NVR systems, Raspberry Pi servers, media servers, and other machines where a runaway container or memory leak could otherwise make the host unreachable.",
        "help_low": "Installs Earlyoom and starts it immediately. Earlyoom watches RAM and swap, then acts before the whole server freezes from low memory.",
        "help_high": "Use this on Debian/Ubuntu-based Linux hosts that run Docker, Frigate, databases, media tools, or other memory-heavy services. Run it on the host machine over SSH, not inside a Docker container. After installation, confirm it is active with systemctl status earlyoom --no-pager. Optional configuration is usually stored in /etc/default/earlyoom; restart it with sudo systemctl restart earlyoom after changes.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
        "notes": "Good for Docker hosts, Frigate servers, Raspberry Pi servers, low-RAM systems, and machines that have frozen before. If Earlyoom keeps triggering, investigate container memory usage, Frigate settings, swap usage, and logs instead of only relying on Earlyoom.\n\nUseful follow-up commands:\njournalctl -u earlyoom -n 100 --no-pager\nfree -h\ndocker stats\nsystemctl status earlyoom --no-pager",
    },
    {
        "name": "Check Earlyoom logs",
        "category": "System / Stability",
        "applies_to_type": "generic",
        "command_template": "sudo journalctl -u earlyoom -n 100 --no-pager",
        "short_description": "Show recent Earlyoom activity.",
        "help_low": "Shows whether Earlyoom has recently killed a process.",
        "help_high": "Run this on the Linux host over SSH when you suspect low-memory events. If it shows repeated kills, check which process was selected and investigate memory usage.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Restart Earlyoom",
        "category": "System / Stability",
        "applies_to_type": "generic",
        "command_template": "sudo systemctl restart earlyoom\nsudo systemctl status earlyoom --no-pager",
        "short_description": "Restart Earlyoom after changing its configuration.",
        "help_low": "Restarts the Earlyoom service and shows its status.",
        "help_high": "Use this after editing /etc/default/earlyoom or when checking that the service can start cleanly. It should not interrupt normal services.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Check memory pressure",
        "category": "System / Stability",
        "applies_to_type": "generic",
        "command_template": "free -h\nvmstat 1 5",
        "short_description": "Check RAM, swap, and short-term memory pressure.",
        "help_low": "Shows memory totals, swap use, and a five-second system pressure sample.",
        "help_high": "Run this in SSH on a Linux host when the machine feels slow or containers are unstable. free -h shows available memory; vmstat shows swap activity, CPU wait, and whether the system is under pressure.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Show top memory processes",
        "category": "System / Stability",
        "applies_to_type": "generic",
        "command_template": "ps aux --sort=-%mem | head -n 15",
        "short_description": "List the processes currently using the most memory.",
        "help_low": "Shows the top memory users on a Linux host.",
        "help_high": "Run this over SSH when RAM is high. It helps identify whether a container, database, camera process, or script is consuming memory.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Docker stats once",
        "category": "Docker",
        "applies_to_type": "generic",
        "command_template": "docker stats --no-stream",
        "short_description": "Show one snapshot of Docker container CPU and memory usage.",
        "help_low": "Shows current container resource usage without staying open.",
        "help_high": "Run this on a Docker host over SSH. It is useful for finding a container that is using too much CPU, RAM, disk I/O, or network.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Check Linux service status",
        "category": "Recovery",
        "applies_to_type": "generic",
        "command_template": "systemctl status {{service_name}} --no-pager",
        "short_description": "Show status for one systemd service.",
        "help_low": "Checks whether a Linux service is running.",
        "help_high": "Use this for services such as docker, ssh, smbd, earlyoom, nginx, or cloudflared. Replace service_name with the systemd unit name.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Check OOM and kernel memory errors",
        "category": "System / Stability",
        "applies_to_type": "generic",
        "command_template": "sudo journalctl -k --grep='Out of memory|oom|killed process' -n 100 --no-pager",
        "short_description": "Search kernel logs for out-of-memory events.",
        "help_low": "Checks whether Linux recently killed anything because memory ran out.",
        "help_high": "Run this over SSH after a freeze, reboot, or unexplained service crash. It searches recent kernel messages for OOM-related lines.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Check reboot required",
        "category": "Debian / Ubuntu",
        "applies_to_type": "generic",
        "command_template": "test -f /var/run/reboot-required && cat /var/run/reboot-required || echo 'No reboot-required file found'",
        "short_description": "Check whether Debian/Ubuntu is asking for a reboot.",
        "help_low": "Shows whether updates have requested a reboot.",
        "help_high": "Run this after apt updates. Some kernel or system library updates do not fully apply until a reboot.",
        "where_to_run": "Remote SSH host",
        "risk_level": "safe",
    },
    {
        "name": "Proxmox list guests",
        "category": "Proxmox",
        "applies_to_type": "generic",
        "command_template": "qm list\npct list",
        "short_description": "List Proxmox VMs and containers.",
        "help_low": "Shows Proxmox virtual machines and LXC containers.",
        "help_high": "Run this on a Proxmox node over SSH. It is read-only and helps match Opsbook service records to VMIDs or CTIDs.",
        "where_to_run": "Proxmox node over SSH",
        "risk_level": "safe",
    },
    {
        "name": "Proxmox node status",
        "category": "Proxmox",
        "applies_to_type": "generic",
        "command_template": "pveversion\npvecm status\nsystemctl status pvedaemon pveproxy --no-pager",
        "short_description": "Check Proxmox version, cluster, and web/API services.",
        "help_low": "Checks whether the Proxmox node and web services look healthy.",
        "help_high": "Run this on a Proxmox node over SSH when the web UI or cluster status seems off. It does not change anything.",
        "where_to_run": "Proxmox node over SSH",
        "risk_level": "safe",
    },
    {
        "name": "Proxmox storage status",
        "category": "Proxmox",
        "applies_to_type": "generic",
        "command_template": "pvesm status\ndf -h",
        "short_description": "Show Proxmox storage pools and filesystem usage.",
        "help_low": "Shows Proxmox storage usage and disk space.",
        "help_high": "Run this on a Proxmox node over SSH before backups, uploads, or migrations. It helps catch full storage before it causes failures.",
        "where_to_run": "Proxmox node over SSH",
        "risk_level": "safe",
    },
    {
        "name": "Proxmox guest backup",
        "category": "Proxmox",
        "applies_to_type": "generic",
        "command_template": "vzdump {{service_name}} --mode snapshot --compress zstd --storage {{folder}}",
        "short_description": "Back up one Proxmox VM or container.",
        "help_low": "Creates a snapshot-mode backup for one VMID or CTID.",
        "help_high": "Replace service_name with the VMID or CTID, and folder with the Proxmox storage ID for backups. Check storage space first with Proxmox storage status.",
        "where_to_run": "Proxmox node over SSH",
        "risk_level": "caution",
    },
    {
        "name": "Windows ping device",
        "category": "Windows",
        "applies_to_type": "generic",
        "command_template": "ping {{host}}",
        "short_description": "Check whether a device replies from Windows.",
        "help_low": "Sends ping packets from Windows to the selected host.",
        "help_high": "Run this in PowerShell or Windows Terminal on your local PC. It helps confirm whether a server is reachable on the network. A failed ping can mean the device is down, the IP is wrong, or ping is blocked.",
        "where_to_run": "Local Windows PC",
        "risk_level": "safe",
    },
    {
        "name": "macOS ping device",
        "category": "macOS",
        "applies_to_type": "generic",
        "command_template": "ping {{host}}",
        "short_description": "Check whether a device replies from macOS.",
        "help_low": "Sends ping packets from macOS to the selected host. Press Ctrl+C to stop.",
        "help_high": "Run this in Terminal on your Mac. It keeps pinging until you press Ctrl+C, which is useful for watching a device come back after reboot.",
        "where_to_run": "Local macOS Terminal",
        "risk_level": "safe",
    },
    {
        "name": "Windows open SMB share",
        "category": "Windows",
        "applies_to_type": "generic",
        "command_template": "explorer \\\\{{host}}\\storage",
        "short_description": "Open an SMB share in Windows File Explorer.",
        "help_low": "Opens a Windows network share.",
        "help_high": "Run this from Windows Run, PowerShell, or Command Prompt. Replace storage with the share name you documented. Browser links to SMB shares may be blocked, so this local command is often more reliable.",
        "where_to_run": "Local Windows PC",
        "risk_level": "safe",
    },
]


def seed_initial_data(db: Session) -> None:
    for tag_name in STARTER_TAGS:
        if not db.query(models.Tag).filter_by(name=tag_name).first():
            db.add(models.Tag(name=tag_name))

    for item in STARTER_COMMANDS:
        existing = db.query(models.Command).filter_by(
            name=item["name"], applies_to_type=item.get("applies_to_type", "generic")
        ).first()
        if existing:
            for key, value in item.items():
                setattr(existing, key, value)
        else:
            db.add(models.Command(**item))

    if db.query(models.Recipe).count() == 0:
        recipe = models.Recipe(
            name="Update Docker app from GitHub",
            category="Docker Compose",
            description="A cautious recipe for pulling code, rebuilding a Compose stack, and checking logs.",
            risk_level="caution",
        )
        db.add(recipe)
        db.flush()
        steps = [
            ("SSH into server", "Open an SSH session to the selected device.", None, "ssh {{username}}@{{host}}"),
            ("Go to service folder", "Move into the folder containing docker-compose.yml.", None, "cd {{service_path}}"),
            ("Check git status", "Look for local changes before pulling.", None, "git status"),
            ("Pull latest code", "Fetch and merge the latest code from GitHub.", None, "git pull"),
            ("Rebuild and restart", "Rebuild containers and start them in the background.", None, "docker compose up -d --build"),
            ("Watch logs", "Confirm startup looks healthy. Press Ctrl+C to stop watching.", None, "docker compose logs -f"),
        ]
        for index, (title, explanation, command_id, command_text) in enumerate(steps, start=1):
            db.add(
                models.RecipeStep(
                    recipe_id=recipe.id,
                    position=index,
                    title=title,
                    explanation=explanation,
                    command_id=command_id,
                    command_text=command_text,
                )
            )

    db.commit()
